title: Deepali Kundnani # your name (or website title) here
logo: "/images/Exec pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bioinformatics Ph.D. Student 
  <br>
  Georgia Institute of Technology
  <br><br>
  <img src="/logos/ln.png" width="20" height="20" alt="https://www.linkedin.com/in/deepalik/"> 
  <a href="https://www.linkedin.com/in/deepalik/"> LinkedIn  </a> 
  <br>
  <img src="/logos/gs.jpg" width="20" height="20" alt="https://scholar.google.com/citations?user=RdAQkxwAAAAJ&hl=en&oi=ao">
  <a href="https://scholar.google.com/citations?user=RdAQkxwAAAAJ&hl=en&oi=ao">  Google Scholar </a> 
  <br>
  <img src="/logos/adobe-pdf-icon.svg" width="20" height="20" alt="/pdf/DLK_CV_2021[07]"> 
  <a href="/pdf/DLK_CV_2021[07].pdf">Curriculum Vitae</a> 
  <br><br>
  <img src="/logos/css.jpg" width="20" height="20" alt="https://atlanta.ashanet.org/blog/donation_profiles/deepali-l-kundnani-2/"> 
  <a href="https://atlanta.ashanet.org/blog/donation_profiles/deepali-l-kundnani-2/">Community Service Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-203542525-1 # your Google Analytics tracking ID here