title: Deepali Kundnani # your name (or website title) here
logo: "/images/Exec pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bioinformatics Ph.D. Student 
  <br><br>
  Georgia Institute of Technology
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-203542525-1 # your Google Analytics tracking ID here